from abc import ABC, abstractmethod

class IVariableRepositoryPort(ABC):
    @abstractmethod
    def add(self, variable):...
    @abstractmethod
    def update(self, name):...
    @abstractmethod
    def get(self, name):...
    @abstractmethod
    def isExist(self, name) -> bool:...
    @abstractmethod
    def delete(self, name):...
    @abstractmethod
    def getAll(self):...