from abc import ABC, abstractmethod

class FuzzyEngineInterface(ABC):
    # @abstractmethod
    # def buildVariable(self, variable):...
    # @abstractmethod
    # def addMembership(self, variable, mf, membership):...
    @abstractmethod
    def createVariable(self, name, var_type, universe):...
    @abstractmethod
    def addMembership(self, fuzzy_var_universe, mf, universe):...
    @abstractmethod
    def createRule(self, ant, con):...
