from abc import ABC, abstractmethod

class IFuzzyEnginePort(ABC):
    @abstractmethod
    def createVariable(self, name, var_type, universe):...
    @abstractmethod
    def addMembership(self, fuzzy_var_universe, mf, universe):...
    @abstractmethod
    def createRule(self, ant, con):...
    @abstractmethod
    def getRuleTermAndLabel(self, rule):...